### ISSUE TITLE
DroidJoy_Server Linux

### ISSUE THREAD

**Issue by personrcunha** [grill2010/DroidJoy_Server#1]
I have ubuntu linux, how can i use DroidJoy server?

**Comment by grill2010** [comment]
DroidJoy only works for Windows PCs. There is no server for linux
available, sorry.

Kind regards

**Comment by grill2010** [comment]
As described in the wiki and in the app store DroidJoy only works for Windows PCs. There is no client for Linux available.

**Comment by vishwaravi** [comment]
Can I compile it from source to build linux binary ?
