### ISSUE TITLE
Cant unistall please help

### ISSUE THREAD

**Issue by Flamehere** [grill2010/DroidJoy_Server#3]
It says i cant unistall because its working but it doesnt
I tried to remove file but i make it worse please help

**Comment by grill2010** [comment]
You have to stop it completely before uninstalling it of course.

**Comment by Aman111111123** [comment]
how can i delete droidjoy i made wrost mistake by deleting setup file

**Comment by streamingdv** [comment]
Like every other application, just close it completely either via the task manager or by right clicking on the tray icon and click close. Then use the uninstaller in the installation directory or uninstall via Software in the control panel. If the application is running you can't uninstall it
