### ISSUE TITLE
gamepad issue

### ISSUE THREAD

**Issue by Deadshot1405** [grill2010/DroidJoy_Server#5]
i am using only 1 gamepad but server is response your all gamepad is used but i am use only 1 gamepad and server didn't show other gamepad in free gamepad i am active all Xinput gamepad but server didn't show in free gamepads please help me to fix this issue

**Comment by grill2010** [comment]
Please go to gamepad 2 tab, click activate XInput gamepad AND AFTERWARDS
click Save Config.

Kind Regards

**Comment by Deadshot1405** [comment]
thank you
