### ISSUE TITLE
Can you provide part of the source code of the server？

### ISSUE THREAD

**Issue by ShihaoZhao-2019** [grill2010/DroidJoy_Server#6]
Want to know how the xbox driver is used and how to simulate the xox input through the server

**Comment by grill2010** [comment]
It just uses an open source driver, you can find it here
https://github.com/shauleiz/ScpToolkit
There is an API available as well for C#

**Comment by ShihaoZhao-2019** [comment]
Thank you



At 2022-12-01 17:58:09, "grill2010" ***@***.***> wrote:

It just uses an open source driver, you can find it here
https://github.com/shauleiz/ScpToolkit
There is an API available as well for C#
